# Analisis y predicción de Ventas Parte 2.

In [ ]:
# Primero conectamos con Google Drive (Si esque estamos trabajando en Google Colab).
from google.colab import drive
drive.mount('/content/drive')

In [24]:
# Importamos librerias.
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Cargar los Datos

In [25]:
# Carga el archivo retail_sales.csv en un DataFrame de Pandas.
path = "../data/retail_sales_dataset.csv"
df = pd.read_csv(path)
# Muestra las primeras 10 filas del DataFrame para confirmar que los datos se han cargado correctamente.
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

In [28]:
# Aplicamos una corrección a los nombres de las columnas para mayor comodidad. En minúsculas y sin espacios.
df.columns = df.columns.str.lower().str.replace(" ","_")

# Exploración Inicial de los Datos

In [29]:
# Muestra las últimas 5 filas del DataFrame.
df.tail(5)

,transaction_id,date,customer_id,gender,age,product_category,quantity,price_per_unit,total_amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [30]:
# Utiliza el método info() para obtener información general sobre el DataFrame, incluyendo el número de entradas, nombres de las columnas, tipos de datos y memoria utilizada.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    1000 non-null   int64
 1   date              1000 non-null   object
 2   customer_id       1000 non-null   object
 3   gender            1000 non-null   object
 4   age               1000 non-null   int64
 5   product_category  1000 non-null   object
 6   quantity          1000 non-null   int64
 7   price_per_unit    1000 non-null   int64
 8   total_amount      1000 non-null   int64
dtypes: int64(5), object(4)
memory usage: 70.4+ KB

In [31]:
# Genera estadísticas descriptivas del DataFrame utilizando el método describe().
df.describe()

       transaction_id         age     quantity  price_per_unit  total_amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

# Inspección de los Datos

In [32]:
# Inspecciona los tipos de datos de cada columna utilizando el atributo dtypes.
df.dtypes

transaction_id       int64
date                object
customer_id         object
gender              object
age                  int64
product_category    object
quantity             int64
price_per_unit       int64
total_amount         int64
dtype: object

In [35]:
# Cuenta los valores únicos en la columna Producto utilizando el método value_counts().
df["product_category"].value_counts()

product_category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

In [36]:
# Muestra todos los valores únicos en la columna Tienda utilizando el método unique().
# Los datos no tienen una columna Tienda asi que usaremos Gender en su lugar.
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

# Filtrado de Datos

In [37]:
# Filtra el DataFrame para mostrar solo las filas donde las ventas (Ventas) sean mayores a 50.
# La columna Total Amount viene siendo el equivalente a la venta.
df[df["total_amount"] > 50]

,transaction_id,date,customer_id,gender,age,product_category,quantity,price_per_unit,total_amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
...,...,...,...,...,...,...,...,...,...
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [38]:
# Filtra el DataFrame para mostrar solo las filas donde el precio (Precio) sea menor a 0.5.
# Lo más cercano sería el precio unitario del producto. Pero estos precios unitarios van desde $25 hasta $500.
# Por lo que modificaré el ejercicio a menor a 50.
df[df["price_per_unit"] < 50]

,transaction_id,date,customer_id,gender,age,product_category,quantity,price_per_unit,total_amount
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
11,12,2023-10-30,CUST012,Male,35,Beauty,3,25,75
...,...,...,...,...,...,...,...,...,...
991,992,2023-08-21,CUST992,Female,57,Electronics,2,30,60
994,995,2023-04-30,CUST995,Female,41,Clothing,1,30,30
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [40]:
# Utilizando el método query(), filtra el DataFrame para mostrar las filas donde el producto sea Manzanas y las ventas sean mayores a 30.
# Mismo caso aqui, se modifica para mostrar las ventas donde la Categoría del producto sea Beauty, y la venta sea mayor a 30.
df.query("product_category == 'Beauty' & total_amount > 30")

,transaction_id,date,customer_id,gender,age,product_category,quantity,price_per_unit,total_amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
11,12,2023-10-30,CUST012,Male,35,Beauty,3,25,75
20,21,2023-01-14,CUST021,Female,50,Beauty,1,500,500
24,25,2023-12-26,CUST025,Female,64,Beauty,1,50,50
...,...,...,...,...,...,...,...,...,...
981,982,2023-12-19,CUST982,Female,46,Beauty,3,30,90
989,990,2023-05-25,CUST990,Female,58,Beauty,2,500,1000
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100

# Slicing de Datos

In [41]:
# Selecciona y muestra solo las columnas Producto y Ventas del DataFrame.
# Se adapta a Categoría de Producto y Monto Total.
df[["product_category","total_amount"]]

    product_category  total_amount
0             Beauty           150
1           Clothing          1000
2        Electronics            30
3           Clothing           500
4             Beauty           100
..               ...           ...
995         Clothing            50
996           Beauty            90
997           Beauty           100
998      Electronics           150
999      Electronics           120

[1000 rows x 2 columns]

In [44]:
# Utilizando loc[], selecciona y muestra las filas de la 5 a la 10 (inclusive) y las columnas Producto y Tienda.
# Nuevamente, la columna Tienda no existe por lo que se adapta para el ejercicio a la columna Gender.
df.loc[5:10, ["gender", "product_category"]]

    gender product_category
5   Female           Beauty
6     Male         Clothing
7     Male      Electronics
8     Male      Electronics
9   Female         Clothing
10    Male         Clothing

In [45]:
# Utilizando iloc[], selecciona y muestra las primeras 5 filas y las primeras 3 columnas del DataFrame.
df.iloc[0:5,0:3]

   transaction_id        date customer_id
0               1  2023-11-24     CUST001
1               2  2023-02-27     CUST002
2               3  2023-01-13     CUST003
3               4  2023-05-21     CUST004
4               5  2023-05-06     CUST005